### PR TITLE
Add compositional reprs

### PR DESCRIPTION
**Pull request by philippjfr**
An initial implementation of compositional reprs, which can be improved later.

Some sample outputs for moderately complex dashboards include:

```
Row(
    HTML(str, width=200),
    Spacer(width=30),
    ParamMethod(method),
    Spacer(width=50),
    Column(
        Param(ParameterSets, name='Attractors', width=220),
        Param(Attractors, expand=True, name='Options', width=220)
    )
)
```

```
Column(
    Row(
        Markdown(str, width=170),
        Spacer(width=50),
        Column(
            Markdown(str, height=25, width=400),
            Spacer(height=-15),
            Markdown(str, width=500)
        ),
        Spacer(width=180),
        Column(
            HoloViews(DynamicMap),
            Button(name='Clear selection'),
            Spacer(height=-15)
        ),
        Markdown(str, width=80)
    ),
    Spacer(height=-50),
    Row(
        HoloViews(DynamicMap),
        HoloViews(DynamicMap)
    ),
    Row(
        HoloViews(DynamicMap),
        HoloViews(DynamicMap)
    )
)
```

- [x] Implements #125

### CODE REVIEW

**Comment by jbednar** [comment]
That's a good start, thanks!  I'd rather avoid the parentheses after Column and Row; this is not an eval-able expression, and I think it's better to make that clear (and avoid the extra whitespace).

The representation also doesn't yet achieve indicating how to index into this object, which is a feature of HoloViews reprs that I really find helpful.  For that it would need to have numbers on the Row and Column entries to indicate which how to index the whole structure to reach that part.  But of course implementing that can be postponed...

**Comment by philippjfr** [comment]
How's this:

```
Column
    [0] Row
        [0] Markdown(str, width=170)
        [1] Spacer(width=50)
        [2] Column
            [0] Markdown(str, height=25, width=400)
            [1] Spacer(height=-15)
            [2] Markdown(str, width=500)
        [3] Spacer(width=180)
        [4] Column
            [0] HoloViews(DynamicMap)
            [1] Button(name='Clear selection')
            [2] Spacer(height=-15)
        [5] Markdown(str, width=80)
    [1] Spacer(height=-50)
    [2] Row
        [0] HoloViews(DynamicMap)
        [1] HoloViews(DynamicMap)
    [3] Row
        [0] HoloViews(DynamicMap)
        [1] HoloViews(DynamicMap)
```

**Comment by jbednar** [comment]
Looks fabulous to me!  I can super easily now pull out [0][5] and work with it!

**Comment by jbednar** [comment]
I can't wait to update my `interact()` example to demonstrate how and why `interact()` is now a clear starting point, not a dead end!

**Comment by jbednar** [comment]
I think we need to limit the reprs:

```
Column
    [0] WidgetBox
        [0] FloatSlider(end=2, name='a', start=-2, value=1.7)
        [1] FloatSlider(end=2, name='b', start=-2, value=1.7)
        [2] FloatSlider(end=2, name='c', start=-2, value=0.6)
        [3] FloatSlider(end=2, name='d', start=-2, value=1.2)
        [4] IntSlider(end=20000000, name='n', start=1, value=2000000)
        [5] Select(name='colormap', options={'bgy': ['#fff123', '#fff122', '#fff122', '#fff022',
'#fff021', '#fcf021', '#f9f021', '#f5f021', '#f2f020', '#eef020', '#eaef20', '#e7ef20', '#e3ef1f',
'#dfef1f', '#dcee1f', '#d8ee1f', '#d4ee1e', '#d1ee1e', '#cded1e', '#c9ed1e', '#c6ed1e', '#c2ec1d',
'#beec1d', '#bbec1d', '#b7eb1d', '#b3eb1d', '#b0ea1c', '#acea1c', '#a8ea1c', '#a4e91c', '#a1e91c',
'#9de81c', '#99e81c', '#95e71b', '#91e71b', '#8ee61b', '#8ae61b', '#86e51b', '#82e51b', '#7ee41b',
'#7ae31b', '#76e31a', '#72e21a', '#6ee21a', '#6ae11a', '#66e01a', '#62e01a', '#5edf1a', '#5ade1a',
... 5 pages of output ...
'#0b017e', '#0a017c', '#09017a', '#090178', '#080276', '#070274', '#060272', '#060270', '#05026e', 
'#04026c', '#030269', '#030267', '#020265', '#010263', '#010261', '#00025f', '#00025d', '#00025b', 
'#000259', '#000257', '#000255', '#000154', '#000152', '#000150', '#00004e'])
    [1] interactive(function, manual_name=Run Interact)
```

**Comment by philippjfr** [comment]
>I think we need to limit the reprs:

Yes, I'll add a function to generate shortened reprs for parameter values.

**Comment by philippjfr** [comment]
@jbednar Mind playing around a bit?

**Comment by jbednar** [comment]
Looks great to me:

```
Column
    [0] WidgetBox
        [0] FloatSlider(end=2, name='a', start=-2, value=1.7)
        [1] FloatSlider(end=2, name='b', start=-2, value=1.7)
        [2] FloatSlider(end=2, name='c', start=-2, value=0.6)
        [3] FloatSlider(end=2, name='d', start=-2, value=1.2)
        [4] IntSlider(end=20000000, name='n', start=1, value=2000000)
        [5] Select(name='colormap', options={'bgy': ['#fff123', ...}, value=['#b3fef5', '#b0fef5', ...])
    [1] interactive(function, manual_name='Run Interact')
```

**Pull request merged**
