### PR TITLE
New style readme

### PR DESCRIPTION
**Pull request by jsignell**
image

### CODE REVIEW

**Comment by jbednar** [comment]
Can the first badge under Latest release be renamed to say what it is?  (github?  tag?)

**Comment by jsignell** [comment]
Yeah wasn't quite sure what to do about the release and the tag. I am basing it on https://github.com/pyviz/panel/tags and https://github.com/pyviz/panel/releases - but that isn't tightly tied in with our travis release builds. Those build when a tag has a certain format.

**Comment by jsignell** [comment]
I changed it to say tag as well. Also I changed the badges that don't indicate status to be 
 blues/purples same as on on the status-dashboard

image

**Comment by jbednar** [comment]
Looks good.  Can we have a badge for "conda|pyviz/label/dev" under Latest dev release as well?

**Comment by jsignell** [comment]
I don't think that badge exists unfortunately. I asked about it and can request it on the shield repo.

**Comment by jbednar** [comment]
Ok, thanks.

**Comment by jsignell** [comment]
For the record I requested the labelled channel support here: https://github.com/badges/shields/issues/2955

**Comment by jsignell** [comment]
wait @jbednar didn't you mean to merge this?

**Comment by jbednar** [comment]
Yes, this should be merged.  I didn't mean to merge it myself, but I didn't mean to close it either!  Must have somehow had a stray click; sorry for the confusion!  Please do restore it and merge it.

**Comment by jsignell** [comment]
I restored it but I don't have the power to reopen and merge

**Pull request merged**
