### PR TITLE
Rough implementation of GridSpec

### PR DESCRIPTION
**Pull request by philippjfr**
Implements a GridSpec layout which allows declaring an NxM grid and assigning objects to the grid cells. Here is an example of a 3x3 grid:

screen shot 2018-09-06 at 6 33 17 pm

- [ ] Invert indexing coordinates (rows then columns)
- [ ] Improve width/height setting logic
- [ ] Fix vertical margin issues
- [ ] Add unit tests
- [ ] Add documentation

### CODE REVIEW

**Comment by jbednar** [comment]
Wow, you are on a roll!

**Comment by jbednar** [comment]
What happens when a grid cell is empty?

**Comment by jbednar** [comment]
Would it be possible for the resulting grid to span the entire page area available (in a server context) or the entire width available (in a notebook context), and to responsively resize, with each item in a grid cell centered by default?  That would be an immediate decent-looking and usable dashboard with very little work for users.

**Comment by philippjfr** [comment]
>What happens when a grid cell is empty?

screen shot 2018-09-06 at 10 35 08 pm

>Would it be possible for the resulting grid to span the entire page area available (in a server context) or the entire width available (in a notebook context), and to responsively resize, with each item in a grid cell centered by default?

I don't think this will work right now, but the new widget work at least theoretically makes that possible if all the other issues can be resolved.

**Comment by jbednar** [comment]
Sounds good, thanks.

**Comment by philippjfr** [comment]
Thanks, I tried the bokeh ``GridSpec`` initially but it didn't do quite what we needed. That said I can't recall why, so I should go back before this is merged and compare/contrast the two implementations.

**Comment by mattpap** [comment]
`GridSpec` was added for a very particular task in one of bokeh's examples (removed at this point), so refining it is an option, especially there are no tests for it and it wasn't every publicized properly.

**Comment by philippjfr** [comment]
Okay, I remember now. One of the main usecases for a `GridSpec` is to assign individual plots to multiple grid cells, the implementation currently in bokeh does not seem to allow for that. When assigning to multiple cells at once you have to provide a list of plots, so really it's just a different way of building the grid yourself and works nothing like matplotlib's `GridSpec`.

**Comment by jbednar** [comment]
Sounds like once panel's GridSpec is solid, Bokeh's GridSpec should either be removed with a pointer to use Panel instead, or else panel's GridSpec should be split into a Bokeh-only implementation with a panel-specific extension on top (i.e. one that understands Panel objects, not just Bokeh models).

**Comment by philippjfr** [comment]
We should definitely consider that. One reason why it might be weird to do that is that this implementation of GridSpec combines both layout and sizing, i.e. inserting an object into the grid defines the size of the plot. This is what makes it possible and what it means to assign a plot/model to multiple grid cells. It may be weird to mess with the sizes of bokeh models directly like that if this were added to bokeh itself, but I'd be happy to file an issue on bokeh to start that discussion.

**Pull request closed without merging**
