### PR TITLE
Added definition_order parameter to CrossSelector

### PR DESCRIPTION
**Pull request by jlstevens**
Right now you can't specify any chosen ordering in the selected list on the right side of a cross-selector as the filtering forces the items into the definition order for `options`. Note that when you set the order via `value`, the widget temporarily accepts the chosen ordering before reverting to definition order.

In some situations, you want to specify the ordering of the selected list based on the ordering you add/remove items to/from it. This PR adds a `definition_order` parameter that you can set to `False` to allow this use case.

I'm not entirely sure that `self._lists[selected].values` is the right set of values here but it does seem to work correctly in my (limited) testing. At the very least I no longer see the reordering back to definition order.

### CODE REVIEW

**Comment by philippjfr** [comment]
Two comments:

1) If you add options dynamically do we need special handling to ensure that this option is respected?

2) I'd like to see a test.

**Comment by jlstevens** [comment]
> If you add options dynamically do we need special handling to ensure that this option is respected?

I don't think so. Adding options dynamically seems to work though any selection is cleared (true before this PR as well).

> I'd like to see a test.

Agreed.

**Comment by jlstevens** [comment]
To recap the behavior I observed prior to this PR (and that is still present):

* Adding to the `options` dynamically resets any selection even if the selected items are members of the new options.
* Shrinking `options` does seem to filter out the selection on the right side without deselecting them and moving them to the left side.

The former point is probably a bug but I think the fix is outside the scope of this PR.

**Comment by philippjfr** [comment]
Looks good. Happy to merge.

**Pull request merged**
