### PR TITLE
Ensure that events are not launched from the wrong thread

### LINKED ISSUE #344: _pending_writes should be non-None when we have a document lock
```python
import panel as pn
import tkinter as tk
from threading import Thread
from panel.io import get_server
from functools import partial

slider = pn.widgets.FloatSlider()

import asyncio


def get_server_in_thread(**kwargs):
    asyncio.set_event_loop(asyncio.new_event_loop())
    get_server(**kwargs)

class Display():

    def __init__(self):
        Thread(target=partial(get_server_in_thread,panel=slider,start=True,show=True,port=5010)).start()
        self.root = tk.Tk()
        self.slider = tk.Scale(self.root, from_=0., to=1., resolution=0.1,
                               orient=tk.HORIZONTAL, command=self.on_slider_change)
        self.slider.pack()
        self.root.mainloop()


    def on_slider_change(self, event):
        slider.value = float(event)

display = Display()
```

ezgif com-video-to-gif (2)

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes #344 

@xavArtley Could you test this?

### CODE REVIEW

**Comment by xavArtley** [comment]
it fails on the firs call:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "D:\CIVA_RP\civa-rep\src_python\civa_utils\bridgeJavaPython\dev\tk_app.py", line 34, in on_slider_change
    slider.value = float(event)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\param\parameterized.py", line 246, in _f
    return f(self, obj, val)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\param\__init__.py", line 614, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\param\parameterized.py", line 246, in _f
    return f(self, obj, val)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\param\parameterized.py", line 775, in __set__
    obj.param._call_watcher(watcher, event)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\param\parameterized.py", line 1371, in _call_watcher
    watcher.fn(self_._update_event_type(watcher, event, self_.self_or_cls.param._TRIGGER))
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\viewable.py", line 567, in param_change
    self._update_model(events, msg, root, model, doc, comm)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\viewable.py", line 547, in _update_model
    model.update(**msg)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\core\has_props.py", line 376, in update
    setattr(self, k, v)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\core\has_props.py", line 280, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\core\property\descriptors.py", line 545, in __set__
    self._internal_set(obj, value, setter=setter)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\core\property\descriptors.py", line 769, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\core\property\descriptors.py", line 838, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\core\property\descriptors.py", line 915, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\model.py", line 678, in trigger
    super(Model, self).trigger(attr, old, new, hint=hint, setter=setter)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\util\callback_manager.py", line 161, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\document.py", line 1004, in _notify_change
    self._trigger_on_change(event)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\document.py", line 1099, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\document.py", line 1112, in _with_self_as_curdoc
    return f()
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\document.py", line 1098, in invoke_callbacks
    cb(event)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\document.py", line 668, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\events.py", line 244, in dispatch
    super(ModelChangedEvent, self).dispatch(receiver)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\events.py", line 126, in dispatch
    receiver._document_patched(self)
  File "D:\CIVA_RP\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\server\session.py", line 214, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
```

**Comment by philippjfr** [comment]
That's because I inverted the logic 🤦‍♂️ 

Pushing a fix now.

**Comment by philippjfr** [comment]
Okay, fixed.

**Comment by xavArtley** [comment]
Yeah great it works

**Pull request merged**
