### PR TITLE
Compatibility for new bokeh layout system

### PR DESCRIPTION
**Pull request by philippjfr**
Currently bokeh layouts are going through a major refactor. This PR will try to maintain compatibility with that bokeh branch (https://github.com/bokeh/bokeh/pull/8085) while staying up to date with panel master.

Things that need fixing:

- [x] Custom (Vega/Plotly) models broken
- [x] Widget sizing completely broken
- [x] Widgets (specifically sliders and buttons) often do not allocate enough vertical space especially when displayed on their own (need at least some padding)
- [x] Tabs are completely broken
- [x] Column/Rows do not update when children are modified
- [x] Widgets don't line up even if given same width/height
- [x] Button.clicks attribute was removed
- [x] "bk-widgetbox" css class is very ugly and does not improve spacing issues mentioned above
- [ ] Widgets do not update in response to changes in their height/width

I'll be adding new items as I discover them and ticking off issues when they're fixed

### CODE REVIEW

**Comment by DancingQuanta** [comment]
Trying out Bokeh version `1.1.0dev2` with `panel.Pipeline` and changing the transition buttons' widths
```
pipeline = pn.pipeline.Pipeline(stages, debug=True)

# Change width of buttons
pipeline.layout[0][1]._widget_box.width = 100
pipeline.layout[0][2]._widget_box.width = 100

pipeline.layout.servable()
```
Modifying the widths have no effect with this version of bokeh.

**Comment by philippjfr** [comment]
This PR is pretty outdated, I'll probably push an entirely new PR for compatibility fixes and adding new features.

**Comment by philippjfr** [comment]
>Modifying the widths have no effect with this version of bokeh.

I've already raised this issue upstream with bokeh.

**Comment by DancingQuanta** [comment]
Could you give the reference to bokeh issue please?

**Comment by philippjfr** [comment]
I'm going to merge this and further development can happen on new PRs.

**Pull request merged**
